// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQtF08OaIlVOdV9vpT6ps7_EQpnHSBcg',
    appId: '1:54250020746:web:05b39328af019ea3be3273',
    messagingSenderId: '54250020746',
    projectId: 'coffin-950d5',
    authDomain: 'coffin-950d5.firebaseapp.com',
    databaseURL: 'https://coffin-950d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffin-950d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA037HOklEvxjRjlpeFNh6RS_ARYPkfKBY',
    appId: '1:54250020746:android:324898fe94c5d895be3273',
    messagingSenderId: '54250020746',
    projectId: 'coffin-950d5',
    databaseURL: 'https://coffin-950d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffin-950d5.appspot.com',
  );
}
